#!/bin/bash

set -e

REPO_DIR="$( cd "$( dirname "$0" )" && pwd )"

mkdir -p /tmp/build
cd /tmp/build
cmake ${REPO_DIR}/extern/fabm/src/drivers/python -DFABM_INSTITUTES="gotm;medusa;mizer" -DFABM_MEDUSA_BASE=${REPO_DIR}/extern/fabm-medusa -DFABM_MIZER_BASE=${REPO_DIR}/extern/fabm-mizer
make install
cd -
